name: Build and Push to ACR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: energyforecastacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        run: |
          docker build \
            -t energyforecastacr.azurecr.io/energy-model-serving:latest \
            -t energyforecastacr.azurecr.io/energy-model-serving:${{ github.sha }} \
            -f src/deployment/Dockerfile .
          docker push energyforecastacr.azurecr.io/energy-model-serving:latest
          docker push energyforecastacr.azurecr.io/energy-model-serving:${{ github.sha }}

      - name: Run endpoint tests
        run: |
          pip install requests numpy
          python tests/test_endpoint.py

      - name: Summary
        run: |
          echo "‚úÖ Image built and pushed to ACR"
          echo "üì¶ Tag: energyforecastacr.azurecr.io/energy-model-serving:${{ github.sha }}"
          echo "üåê Live endpoint: http://energy-model-saurav.westeurope.azurecontainer.io:5001"
